services:
    Tbn\GetterTraitBundle\Generator\ReflectionExtractor:
        public: true
        class: "Tbn\\GetterTraitBundle\\Generator\\ReflectionExtractor"
        arguments:
            - "@property_info.phpstan_extractor"

    Tbn\GetterTraitBundle\Command\EntitiesCommand:
        public: true
        class: "Tbn\\GetterTraitBundle\\Command\\EntitiesCommand"
        arguments:
            - '@Tbn\GetterTraitBundle\Generator\Generator'
        tags:
            - { name: 'console.command', command: 'generate:getter:traits' }
    Tbn\GetterTraitBundle\Generator\Generator:
        public: true
        class: "Tbn\\GetterTraitBundle\\Generator\\Generator"
        arguments:
            - '@Tbn\GetterTraitBundle\Generator\ReflectionExtractor'
            - '@Tbn\GetterTraitBundle\Generator\EntityGenerator'
    Tbn\GetterTraitBundle\Generator\EntityGenerator:
        public: true
        class: "Tbn\\GetterTraitBundle\\Generator\\EntityGenerator"
        arguments:
            - '@logger'
            - '@Tbn\GetterTraitBundle\Generator\ReflectionExtractor'
            - '@Tbn\GetterTraitBundle\Generator\ArrayConstructorGenerator'

    Tbn\GetterTraitBundle\Generator\ArrayConstructorGenerator:
        public: true
        class: "Tbn\\GetterTraitBundle\\Generator\\ArrayConstructorGenerator"
        arguments:
            - '@Tbn\GetterTraitBundle\Generator\ReflectionExtractor'
